apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ue2fpysgp-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-36b02bf75a.mbjs.p3.openshiftapps.com/rhtap/rhtap-qe:c154016e9881806f9b56ed79d89f9b4621de7be8@sha256:97d1145ac738b719f5cfa2ec75093b0907e61efe5b9e2d98b2deb38123942c6e
          name: container-image
